version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: senecastats
  MYSQL_USER: aja
  MYSQL_PASSWORD: admin123

services:
  mysql_db:
    image: mysql # seneca-stats-service repository URI here
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_HOST: localhost

  seneca-stats-service:
    image: 582593384005.dkr.ecr.us-west-2.amazonaws.com/seneca_stats_service # seneca-stats-service repository URI here
    container_name: seneca-stats-service
    restart: on-failure:10
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    depends_on:
      - mysql_db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
      SERVER_PORT: 3000
  
  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8080:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db

volumes:
  mysql-data: