version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: senecastats
  MYSQL_USER: aja
  MYSQL_PASSWORD: admin123

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_HOST: localhost

  seneca-stats-service:
    container_name: seneca-stats-service
    restart: on-failure:10
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - "/app/node_modules"
    ports:
      - '3000:3000'
    depends_on:
      - mysql_db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
      SERVER_PORT: 3000
  
  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db